### ISSUE TITLE
Make it possible for admins to post comments on behalf of contributors

### ISSUE THREAD

**Issue by yourcelf** [AdmitHub/Telescope#1]

**Comment by yourcelf** [comment]
Good news: this is possible already in the latest version of Telescope.  As I was starting to implement I realized that it was already there.

**Comment by AndrewMagliozzi** [comment]
Really?  How?  I'm not sure I saw an edit button for comments.

**Comment by yourcelf** [comment]
Oops, my confusion. You can make posts on behalf of others.  I'll try to get to this today.

**Comment by AndrewMagliozzi** [comment]
Thanks!

**Comment by yourcelf** [comment]
OK, fixed and deployed.  I've both added a [PR to core](https://github.com/TelescopeJS/Telescope/pull/1145) and added a [stopgap package](https://github.com/AdmitHub/Telescope/tree/master/packages/comment-author-stopgap) which monkeypatches the same changes.

A credit to the new Telescope codebase that this change was very simple to do.

**Comment by AndrewMagliozzi** [comment]
@yourcelf there is some strange behavior with this fix.  The dropdown list is showing some users who are not meant to be shown (just ordinary users).  It's also not showing some of our Officers who are being displayed on the contributors page.

**Comment by yourcelf** [comment]
Fixed in f87421209cbfd225248bd548e1f8e2965dc8b7ad.
