### ISSUE TITLE
Add thumbnail images to the forum

### ISSUE THREAD

**Issue by AndrewMagliozzi** [AdmitHub/Telescope#11]
There is a telescope package for this:

https://github.com/TelescopeJS/Telescope/tree/master/packages/telescope-embedly

I've also added our Embedly API key to the settings on prod.  

I've shared the account info with you @yourcelf too.  I think we just need to add this image to our custom design.

@constantx can advise about specific look or just modify the style after we have the thumbnails in place.

In the meantime, we're doing a super hack by placing the image in the body of the question.

**Comment by AndrewMagliozzi** [comment]
you can see thumbnails working here too: http://demo2.telescopeapp.org/

**Comment by yourcelf** [comment]
What do you envision the thumbnails to be of in our installation?

The built-in embedly plugin takes a snapshot of the target page of the URL for a post.  But none of our posts have URLs -- they're all "self" posts, just a title and sometimes a body.

**Comment by AndrewMagliozzi** [comment]
Ideally an image Dan uploads himself.

**Comment by yourcelf** [comment]
So thumbnails should be editable by admins/officers?  Should they be editable by regular users?

**Comment by yourcelf** [comment]
BTW, if we want to explicitly choose the thumbnail, we'll need to do this custom.  The embedly implementation ties the thumbnail to the post URL and doesn't allow you to choose your own thumbnail.

**Comment by yourcelf** [comment]
Looks like this is implemented in https://github.com/AdmitHub/Telescope/pull/12 ?

**Comment by AndrewMagliozzi** [comment]
Yes
