### ISSUE TITLE
Errors preventing form submission on user type

### ISSUE THREAD

**Issue by yourcelf** [AdmitHub/Telescope#24]
https://admithub.slack.com/files/dp/F0G5MVBPE/screen_shot_2015-12-08_at_12.04.05_pm.png

**Comment by AndrewMagliozzi** [comment]
submit button not working here: 
![image](https://cloud.githubusercontent.com/assets/1189217/13639055/ec4e4044-e5dc-11e5-8fe1-0290d152ddbf.png)
