### ISSUE TITLE
Post count reset

### ISSUE THREAD

**Issue by pcorey** [AdmitHub/Telescope#8]
From Kirk:

> the #s on posts are looking like they were reset?
> https://files.slack.com/files-pri/T049EGE20-F0BT9R2CT/screen_shot_2015-10-05_at_4.53.18_pm.png

**Comment by pcorey** [comment]
I'm guessing this had something to do with the Telescope upgrade. We should investigate how this happened so it won't happen again, and then potentially run a migration to re-populate this field.

**Comment by yourcelf** [comment]
Fixed in https://github.com/AdmitHub/Telescope/commit/67a50828ae307572ba1471432409e9a1ea67ef85
